service: smartpie

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  profile: personal

functions:
  main:
    handler: handler.handler
    memorySize: 128
    events:
      - alexaSmartHome: ${file(./secrets.yml):skillId}
